# -*- coding: utf-8 -*-
# pylint: disable=W0614,W0611,W0622
# flake8: noqa
# isort:skip_file
import openpyxl
import logging
import sys
import xlrd

logger = logging.getLogger('adsorption_file_parser')
logger.setLevel(logging.DEBUG)

# create console handler
ch = logging.StreamHandler(stream=sys.stdout)
ch.setLevel(logging.INFO)

# add the handlers to the logger
logger.addHandler(ch)

# Solve version shenanigans on conda-build
try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import __version__
except ImportError:
    # -- Source mode --
    # use setuptools_scm to get the current version from src using git
    from setuptools_scm import get_version as _gv
    from os import path as _path
    __version__ = _gv(_path.join(_path.dirname(__file__), _path.pardir))


class ParsingError(Exception):
    """Raised when parsing fails."""


_SUPPORTED_FORMATS = {
    'smsdvs': ('xlsx', ),
    'bel': ('csv', 'xl', 'dat'),
    'mic': ('xl', ),
    '3p': ('xl'),  # 'jwgbt'),
    'qnt': ('txt-raw', ),
    'generic': ('csv', 'xls'),
}


def guess_manufacturer_fmt(path):
    """
    From a file generated by commercial apparatus, figure out
    what is the manufacturer and the file format.

    Parameters
    ----------
    path: str
        the location of the file.

    Returns
    -------
    manufacturer : {'mic', 'bel', '3p', ...}
        Manufacturer of the apparatus.
    fmt : {'xl', 'txt', ...}
        The format of the isotherm.
    """

    # Text formats
    try:
        with open(path, 'r', encoding='cp1252') as file:
            lines = "\n".join(file.readline() for _ in range(6))
            if 'Quantachrome Instruments' in lines:
                return 'qnt', 'txt-raw'
            if 'BELSORP-max' in lines or 'Instrument S/N' in lines:
                return 'bel', 'dat'
            if 'File Name,' in lines or 'Date of measurement,' in lines:
                return 'bel', 'csv'
    except Exception:
        pass

    try:
        with open(path, 'r', encoding='shift_jis') as file:
            lines = "\n".join(file.readline() for _ in range(6))
            if 'BELSORP-max' in lines or '装置情報' in lines:
                return 'bel', 'dat'
            if 'ファイル名,' in lines or '測定日,' in lines:
                return 'bel', 'csv'
    except Exception:
        pass

    # Excel formats
    try:
        workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
        if 'DVS Data' in workbook:
            return 'smsdvs', 'xlsx'
        if 'Info' in workbook or 'Summary' in workbook:
            return '3p', 'xl'
    except Exception:
        pass

    try:
        workbook = xlrd.open_workbook(path, encoding_override='latin-1')
        if 'AdsDes' in workbook.sheet_names():
            return 'bel', 'xl'
        if 'Isotherm Tabular Report' in workbook.sheet_names():
            return 'mic', 'xl'
        sheet = workbook.sheet_by_index(0)
        for row in range(5):
            row_content = ' '.join(sheet.row_values(row))
            if ('3Flex' in row_content or 'Full Report Set' in row_content
                or 'Micromeritics' in row_content or 'MicroActive' in row_content):
                return 'mic', 'xl'
    except Exception:
        pass

    # Try generic formats last
    try:
        workbook = xlrd.open_workbook(path)
        if workbook.nsheets > 0:
            return 'generic', 'xls'
    except Exception:
        pass

    # If a text file has commas on most lines, it is probably a CSV
    try:
        with open(path, encoding='utf-8') as file:
            lines = file.readlines()
            numsep = sum(1 for s in lines if ',' in s)
            if numsep > 0.8 * len(lines):
                return 'generic', 'csv'
    except Exception:
        pass

    # We could not find match
    return 'unknown', 'unknown'


def read(path, manufacturer='guess', fmt='guess', **options):
    """
    Parse a file generated by commercial apparatus.

    Parameters
    ----------
    path: str
        the location of the file.
    manufacturer : {'mic', 'bel', '3p', ... or 'guess'}
        Manufacturer of the apparatus. Default is 'guess'.
    fmt : {'xl', 'txt-raw', ... or 'guess'}
        The format of the import for the isotherm.
        Default is 'guess'.

    Returns
    -------
    meta: dict
        the metadata
    data: dict
        all available data
    """

    if manufacturer == 'guess' or fmt == 'guess':
        guess_man, guess_fmt = guess_manufacturer_fmt(path)
        if manufacturer == 'guess':
           manufacturer = guess_man
        if fmt == 'guess':
           fmt = guess_fmt

    if manufacturer not in _SUPPORTED_FORMATS:
        raise ParsingError(
            f'Currently available manufacturers are {list(_SUPPORTED_FORMATS.keys())})'
        )

    if fmt not in _SUPPORTED_FORMATS[manufacturer]:
        raise ParsingError(f'Currently available formats are {_SUPPORTED_FORMATS[manufacturer]}')

    if manufacturer == 'smsdvs' and fmt == 'xlsx':
        from .sms_dvs_excel import parse
    elif manufacturer == 'mic' and fmt == 'xl':
        from .mic_excel import parse
    elif manufacturer == 'bel':
        if fmt == 'xl':
            from .bel_excel import parse
        elif fmt == 'csv':
            from .bel_csv import parse
        elif fmt == 'dat':
            from .bel_dat import parse
    elif manufacturer == '3p':
        if fmt == 'xl':
            from .trp_excel import parse
        elif fmt == 'jwgbt':
            from .trp_xml import parse
    elif manufacturer == 'qnt' and fmt == 'txt-raw':
        from .qnt_txt import parse
    elif manufacturer == 'generic':
        if fmt == 'csv':
            from .generic_csv import parse
        elif fmt == 'xls':
            from .generic_excel import parse
    else:
        raise ParsingError('Something went wrong.')

    return parse(path, **options)
