name: CI/CD

on:
  [push, pull_request, workflow_dispatch]

jobs:
  linting-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: '**/setup.cfg'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools
        pip --version
    - name: Install package
      run: |
        pip install .[dev]
    - name: Run lint checks
      run: |
        isort --verbose --check-only --diff src tests
        flake8 src tests

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version : ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.cfg'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools
        pip --version
    - name: Install package
      run: |
        pip install -e .[dev]
    - name: Run tests
      run: |
        pytest --cov --cov-report=term-missing -vv

  build-publish:
      runs-on: ubuntu-latest
      needs: [linting-checks, unit-tests]
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install build
          python -m pip install --upgrade setuptools wheel
          pip --version
      - name: Install package
        run: |
          pip install .[dev]
          python -c "from importlib.metadata import version; print(version('adsorption_file_parser'))"
      - name: Build wheels
        run: python -m build
      - name: Publish 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Test PyPI
        run: pip install adsorption-file-parser
      - name: GH 🐱🐙 Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
